services:
  backend:
    build:
      context: ./hereapp-backend
      dockerfile: Dockerfile
    container_name: backend_app
    ports:
      - "8083:8083"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
